name: apprenticehsips-provider-dashboard-$(rev:r)

pool:
  name: RSConnect
  
trigger:
  branches:
    include:
    - main

  paths:
    exclude:
    - azure-pipelines.yml
    
resources:
  repositories:
    - repository: posit-deploy
      type: git
      name: ESFA-Data-Science/posit-deploy
      
extends:
  template: deploy.yml@posit-deploy
  parameters:
    appName: apprenticeships-provider-dashboard
    environments:
    - name: Pre-Production
      appId: None
    - name: Production
      appId: None
    approvers: |
     cameron.race@education.gov.uk
     richard.bielby@education.gov.uk